// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Bx4XnPYwq-_Z53Kyv9PxLSm41oiGONg',
    appId: '1:335241640055:web:9c8504010e8bd02060ae72',
    messagingSenderId: '335241640055',
    projectId: 'instagram-clone-c396d',
    authDomain: 'instagram-clone-c396d.firebaseapp.com',
    storageBucket: 'instagram-clone-c396d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvXnoMvj_mq8NzMsRFyDedV9EuMSBS_wQ',
    appId: '1:335241640055:android:9de6bc70fb2dc17b60ae72',
    messagingSenderId: '335241640055',
    projectId: 'instagram-clone-c396d',
    storageBucket: 'instagram-clone-c396d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJeh_WuRiXaL1VgR8OTfrhl5JqrGXjaNE',
    appId: '1:335241640055:ios:b79425f1fa6a21da60ae72',
    messagingSenderId: '335241640055',
    projectId: 'instagram-clone-c396d',
    storageBucket: 'instagram-clone-c396d.appspot.com',
    iosClientId: '335241640055-2gjc2ggn3vscq0dogol61ovrhd5bofqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJeh_WuRiXaL1VgR8OTfrhl5JqrGXjaNE',
    appId: '1:335241640055:ios:363920d7d4aaecb260ae72',
    messagingSenderId: '335241640055',
    projectId: 'instagram-clone-c396d',
    storageBucket: 'instagram-clone-c396d.appspot.com',
    iosClientId: '335241640055-ajr6b7lmfa3ut07jg5s9ab9nft9fhcjv.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramFlutter.RunnerTests',
  );
}
